sudo: false
dist: trusty
language: python
python:
  - "3.6"

cache: pip

install:
  - pip3 install mypy==0.530 git+https://github.com/PyCQA/pycodestyle.git@4510fa0#egg=pycodestyle flake8==3.4.1

script:
  - bin/repo-lint
